### ISSUE TITLE
Is this support android platform

### ISSUE THREAD

**Issue by RR-Reddy** [beerstorm-net/the_apple_sign_in#1]

**Comment by zeusbaba** [comment]
Thnx for your feedback @RR-Reddy  
I recently took over this project from from Tom Gilder, and still in process of refreshing it with more usability.  Soon, I'll _try_ to add `Android´ support as well. 

Feel free to contribute with pull-request

**Comment by zeusbaba** [comment]
i'll close this as it is known limitation. This plugin currently supports only `iOS`
