### ISSUE TITLE
Uint8List to String

### ISSUE THREAD

**Issue by dukaric1991** [beerstorm-net/the_apple_sign_in#3]
Hey, first thanks for migrating to null safety.

Previously in the flutter_apple_sign_in package i had this line of code:

```
  final AppleIdCredential appleIdCredential = result.credential;

  OAuthProvider oAuthProvider = new OAuthProvider("apple.com");
  final AuthCredential credential = oAuthProvider.credential(
    idToken: String.fromCharCodes(appleIdCredential.identityToken),
    accessToken:
        String.fromCharCodes(appleIdCredential.authorizationCode),
  );
```

and it worked fine, and now `idToken` and `accessToken` cannot be set because `identityToken` and `authorizationCode` give error:

`The argument type 'Uint8List?' can't be assigned to the parameter type 'Iterable<int>'.`

**Comment by zeusbaba** [comment]
Hello @dukaric1991 ,  
thnx for this.  
I'll have a better look later today and come back with a response.

**Comment by zeusbaba** [comment]
quick questions;    
- can u plz share the Flutter version you have? simply by running `flutter doctor -v`  
- what you've set in your `pubspec.yaml` for `environment:`

**Comment by dukaric1991** [comment]
I am on Flutter `2.2.0`

```
environment:
  sdk: '>=2.12.0 <3.0.0'
```
I have now tried with these two lines and the error is gone, but i need to try thic code on my mac to see if it works correctly.

```
  Iterable<int> identityToken = appleIdCredential!.identityToken as Iterable<int>;
  Iterable<int> authorizationCode = appleIdCredential.authorizationCode as Iterable<int>;
```

Current code:
```
  final AppleIdCredential? appleIdCredential = result.credential;

  OAuthProvider oAuthProvider = new OAuthProvider("apple.com");
  Iterable<int> identityToken = appleIdCredential!.identityToken as Iterable<int>;
  Iterable<int> authorizationCode = appleIdCredential.authorizationCode as Iterable<int>;
  final AuthCredential credential = oAuthProvider.credential(
    idToken: String.fromCharCodes(identityToken),
    accessToken:
        String.fromCharCodes(authorizationCode),
  );
```

**Comment by zeusbaba** [comment]
I'm using this plugin in all of my Flutter apps, I just did a round of debugging and noticed no issue.    
Can you plz make sure your Flutter version is v2 or higher?  

Just in case, sharing the code snippet from my apps which works flawlessly.  

```
List<Scope> scopes = const [Scope.email, Scope.fullName];  
final AuthorizationResult result = await TheAppleSignIn.performRequests([AppleIdRequest(requestedScopes: scopes)]);   

switch (result.status) {
      case AuthorizationStatus.authorized:
          final appleIdCredential = result.credential;
          final oAuthProvider = OAuthProvider('apple.com');
          final credential = oAuthProvider.credential(
            idToken: String.fromCharCodes(appleIdCredential.identityToken),
            accessToken: String.fromCharCodes(appleIdCredential.authorizationCode),
          );

          final authResult = await FirebaseAuth.instance.signInWithCredential(credential);
          final firebaseUser = authResult.user;
          //  ...persist etc etc....  
          return firebaseUser;  
      case AuthorizationStatus.error:
          // handle error case
      case AuthorizationStatus.cancelled:
          // handle error case
}


```

**Comment by zeusbaba** [comment]
ok now I see, the issue comes from this  
```
environment:
  sdk: '>=2.12.0 <3.0.0'
```  
This requires your  app codebase & implementations to be **strictly null safe** as well.  

Usually, in my apps I use   
```
environment:
  sdk: ">=2.8.0 <3.0.0"
```  
So that this gives me flexibility to make my codebase hybrid (partial null safe)  while using any package that is all null safe.  
It might sound like a workaround but flexibility is always good.

**Comment by zeusbaba** [comment]
did my last suggestion help?  
plz let me know if you have any further questions.

**Comment by zeusbaba** [comment]
no response thus closing this issue assuming it is resolved  
you are welcome to open new issue if you need
