### ISSUE TITLE
Platform check does not work on the web

### ISSUE THREAD

**Issue by bbence84** [beerstorm-net/the_apple_sign_in#9]
Hi! Thanks for this awesome package! :)
There's an issue however that the current implementation for checking if the platform is iOS does not work on web deployment, getting the error: "Error: Unsupported operation: Platform._operatingSystem".
Based on stackoverflow, the following alternative checking mechanisms might work:
https://stackoverflow.com/questions/63704551/flutter-web-platform-check
https://stackoverflow.com/questions/58459483/unsupported-operation-platform-operatingsystem

Thanks!

**Comment by aGubhaju** [comment]
This plugin is specifically for iOS only, there other plugin that works with android + web but requires some configuration on server-side.

**Comment by zeusbaba** [comment]
indeed, this plugin is `iOS` only
